//#line 2 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the path_publisher_ros_tool package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __path_publisher_ros_tool__PATHPUBLISHERCONFIG_H__
#define __path_publisher_ros_tool__PATHPUBLISHERCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace path_publisher_ros_tool
{
  class PathPublisherConfigStatics;

  class PathPublisherConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(PathPublisherConfig &config, const PathPublisherConfig &max, const PathPublisherConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const PathPublisherConfig &config1, const PathPublisherConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, PathPublisherConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const PathPublisherConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, PathPublisherConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const PathPublisherConfig &config) const = 0;
      virtual void getValue(const PathPublisherConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T PathPublisherConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (PathPublisherConfig::* field);

      virtual void clamp(PathPublisherConfig &config, const PathPublisherConfig &max, const PathPublisherConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const PathPublisherConfig &config1, const PathPublisherConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, PathPublisherConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const PathPublisherConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, PathPublisherConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const PathPublisherConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const PathPublisherConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, PathPublisherConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, PathPublisherConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<PathPublisherConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(PathPublisherConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("verbosity"==(*_i)->name){verbosity = boost::any_cast<std::string>(val);}
        if("timer_rate"==(*_i)->name){timer_rate = boost::any_cast<double>(val);}
        if("kos_shift"==(*_i)->name){kos_shift = boost::any_cast<double>(val);}
        if("delta_sigma"==(*_i)->name){delta_sigma = boost::any_cast<double>(val);}
        if("center_x"==(*_i)->name){center_x = boost::any_cast<double>(val);}
        if("center_y"==(*_i)->name){center_y = boost::any_cast<double>(val);}
        if("path_length"==(*_i)->name){path_length = boost::any_cast<double>(val);}
        if("drive_distance"==(*_i)->name){drive_distance = boost::any_cast<double>(val);}
        if("point_distance"==(*_i)->name){point_distance = boost::any_cast<double>(val);}
        if("radius_noise"==(*_i)->name){radius_noise = boost::any_cast<double>(val);}
        if("rotation_noise"==(*_i)->name){rotation_noise = boost::any_cast<double>(val);}
        if("shift_noise"==(*_i)->name){shift_noise = boost::any_cast<double>(val);}
        if("local_scope"==(*_i)->name){local_scope = boost::any_cast<double>(val);}
        if("least_points"==(*_i)->name){least_points = boost::any_cast<int>(val);}
        if("stuck_time"==(*_i)->name){stuck_time = boost::any_cast<double>(val);}
        if("BB_left_bottom_x"==(*_i)->name){BB_left_bottom_x = boost::any_cast<double>(val);}
        if("BB_left_bottom_y"==(*_i)->name){BB_left_bottom_y = boost::any_cast<double>(val);}
        if("BB_top_right_x"==(*_i)->name){BB_top_right_x = boost::any_cast<double>(val);}
        if("BB_top_right_y"==(*_i)->name){BB_top_right_y = boost::any_cast<double>(val);}
        if("road_length"==(*_i)->name){road_length = boost::any_cast<double>(val);}
      }
    }

    std::string verbosity;
double timer_rate;
double kos_shift;
double delta_sigma;
double center_x;
double center_y;
double path_length;
double drive_distance;
double point_distance;
double radius_noise;
double rotation_noise;
double shift_noise;
double local_scope;
int least_points;
double stuck_time;
double BB_left_bottom_x;
double BB_left_bottom_y;
double BB_top_right_x;
double BB_top_right_y;
double road_length;

    bool state;
    std::string name;

    class PUBLISHER_AND_SUBSCRIBER
{
  public:
    PUBLISHER_AND_SUBSCRIBER()
    {
      state = true;
      name = "Publisher_and_subscriber";
    }

    void setParams(PathPublisherConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("path_publisher_topic"==(*_i)->name){path_publisher_topic = boost::any_cast<std::string>(val);}
        if("path_publisher_queue_size"==(*_i)->name){path_publisher_queue_size = boost::any_cast<int>(val);}
      }
    }

    std::string path_publisher_topic;
int path_publisher_queue_size;

    bool state;
    std::string name;

    
}publisher_and_subscriber;

}groups;



//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string verbosity;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double timer_rate;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double kos_shift;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double delta_sigma;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double center_x;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double center_y;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double path_length;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double drive_distance;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double point_distance;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double radius_noise;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double rotation_noise;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double shift_noise;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double local_scope;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int least_points;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double stuck_time;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double BB_left_bottom_x;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double BB_left_bottom_y;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double BB_top_right_x;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double BB_top_right_y;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double road_length;
//#line 42 "/home/kal1-4/anicar_ws/devel/.private/path_publisher_ros_tool/share/path_publisher_ros_tool/cfg/PathPublisher.cfg"
      std::string path_publisher_topic;
//#line 43 "/home/kal1-4/anicar_ws/devel/.private/path_publisher_ros_tool/share/path_publisher_ros_tool/cfg/PathPublisher.cfg"
      int path_publisher_queue_size;
//#line 228 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("PathPublisherConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const PathPublisherConfig &__max__ = __getMax__();
      const PathPublisherConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const PathPublisherConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const PathPublisherConfig &__getDefault__();
    static const PathPublisherConfig &__getMax__();
    static const PathPublisherConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const PathPublisherConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void PathPublisherConfig::ParamDescription<std::string>::clamp(PathPublisherConfig &config, const PathPublisherConfig &max, const PathPublisherConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class PathPublisherConfigStatics
  {
    friend class PathPublisherConfig;

    PathPublisherConfigStatics()
    {
PathPublisherConfig::GroupDescription<PathPublisherConfig::DEFAULT, PathPublisherConfig> Default("Default", "", 0, 0, true, &PathPublisherConfig::groups);
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.verbosity = "";
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.verbosity = "";
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.verbosity = "info";
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<std::string>("verbosity", "str", 0, "Sets the verbosity for this node", "{'enum_description': 'Sets the verbosity for this node', 'enum': [{'srcline': 15, 'description': '', 'srcfile': '/home/kal1-4/anicar_ws/devel/.private/path_publisher_ros_tool/share/path_publisher_ros_tool/cfg/PathPublisher.cfg', 'cconsttype': 'const char * const', 'value': 'debug', 'ctype': 'std::string', 'type': 'str', 'name': 'debug'}, {'srcline': 16, 'description': '', 'srcfile': '/home/kal1-4/anicar_ws/devel/.private/path_publisher_ros_tool/share/path_publisher_ros_tool/cfg/PathPublisher.cfg', 'cconsttype': 'const char * const', 'value': 'info', 'ctype': 'std::string', 'type': 'str', 'name': 'info'}, {'srcline': 17, 'description': '', 'srcfile': '/home/kal1-4/anicar_ws/devel/.private/path_publisher_ros_tool/share/path_publisher_ros_tool/cfg/PathPublisher.cfg', 'cconsttype': 'const char * const', 'value': 'warning', 'ctype': 'std::string', 'type': 'str', 'name': 'warning'}, {'srcline': 18, 'description': '', 'srcfile': '/home/kal1-4/anicar_ws/devel/.private/path_publisher_ros_tool/share/path_publisher_ros_tool/cfg/PathPublisher.cfg', 'cconsttype': 'const char * const', 'value': 'error', 'ctype': 'std::string', 'type': 'str', 'name': 'error'}, {'srcline': 19, 'description': '', 'srcfile': '/home/kal1-4/anicar_ws/devel/.private/path_publisher_ros_tool/share/path_publisher_ros_tool/cfg/PathPublisher.cfg', 'cconsttype': 'const char * const', 'value': 'fatal', 'ctype': 'std::string', 'type': 'str', 'name': 'fatal'}]}", &PathPublisherConfig::verbosity)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<std::string>("verbosity", "str", 0, "Sets the verbosity for this node", "{'enum_description': 'Sets the verbosity for this node', 'enum': [{'srcline': 15, 'description': '', 'srcfile': '/home/kal1-4/anicar_ws/devel/.private/path_publisher_ros_tool/share/path_publisher_ros_tool/cfg/PathPublisher.cfg', 'cconsttype': 'const char * const', 'value': 'debug', 'ctype': 'std::string', 'type': 'str', 'name': 'debug'}, {'srcline': 16, 'description': '', 'srcfile': '/home/kal1-4/anicar_ws/devel/.private/path_publisher_ros_tool/share/path_publisher_ros_tool/cfg/PathPublisher.cfg', 'cconsttype': 'const char * const', 'value': 'info', 'ctype': 'std::string', 'type': 'str', 'name': 'info'}, {'srcline': 17, 'description': '', 'srcfile': '/home/kal1-4/anicar_ws/devel/.private/path_publisher_ros_tool/share/path_publisher_ros_tool/cfg/PathPublisher.cfg', 'cconsttype': 'const char * const', 'value': 'warning', 'ctype': 'std::string', 'type': 'str', 'name': 'warning'}, {'srcline': 18, 'description': '', 'srcfile': '/home/kal1-4/anicar_ws/devel/.private/path_publisher_ros_tool/share/path_publisher_ros_tool/cfg/PathPublisher.cfg', 'cconsttype': 'const char * const', 'value': 'error', 'ctype': 'std::string', 'type': 'str', 'name': 'error'}, {'srcline': 19, 'description': '', 'srcfile': '/home/kal1-4/anicar_ws/devel/.private/path_publisher_ros_tool/share/path_publisher_ros_tool/cfg/PathPublisher.cfg', 'cconsttype': 'const char * const', 'value': 'fatal', 'ctype': 'std::string', 'type': 'str', 'name': 'fatal'}]}", &PathPublisherConfig::verbosity)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.timer_rate = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.timer_rate = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.timer_rate = 5.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<double>("timer_rate", "double", 0, "publisher frequency", "", &PathPublisherConfig::timer_rate)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<double>("timer_rate", "double", 0, "publisher frequency", "", &PathPublisherConfig::timer_rate)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.kos_shift = -0.5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.kos_shift = 0.5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.kos_shift = -0.2;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<double>("kos_shift", "double", 0, "distance from vehicle frame id referred position to real vehicle center point", "", &PathPublisherConfig::kos_shift)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<double>("kos_shift", "double", 0, "distance from vehicle frame id referred position to real vehicle center point", "", &PathPublisherConfig::kos_shift)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.delta_sigma = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.delta_sigma = 0.1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.delta_sigma = 0.01;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<double>("delta_sigma", "double", 0, "delta angle to generate sample path", "", &PathPublisherConfig::delta_sigma)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<double>("delta_sigma", "double", 0, "delta angle to generate sample path", "", &PathPublisherConfig::delta_sigma)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.center_x = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.center_x = 15.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.center_x = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<double>("center_x", "double", 0, "x axis value of center point of map", "", &PathPublisherConfig::center_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<double>("center_x", "double", 0, "x axis value of center point of map", "", &PathPublisherConfig::center_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.center_y = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.center_y = 15.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.center_y = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<double>("center_y", "double", 0, "y axis value of center point of map", "", &PathPublisherConfig::center_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<double>("center_y", "double", 0, "y axis value of center point of map", "", &PathPublisherConfig::center_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.path_length = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.path_length = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.path_length = 6.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<double>("path_length", "double", 0, "length of a published path", "", &PathPublisherConfig::path_length)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<double>("path_length", "double", 0, "length of a published path", "", &PathPublisherConfig::path_length)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.drive_distance = 0.1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.drive_distance = 3.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.drive_distance = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<double>("drive_distance", "double", 0, "drive distance before update path", "", &PathPublisherConfig::drive_distance)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<double>("drive_distance", "double", 0, "drive distance before update path", "", &PathPublisherConfig::drive_distance)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.point_distance = 0.005;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.point_distance = 0.5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.point_distance = 0.02;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<double>("point_distance", "double", 0, "distance between two points", "", &PathPublisherConfig::point_distance)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<double>("point_distance", "double", 0, "distance between two points", "", &PathPublisherConfig::point_distance)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.radius_noise = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.radius_noise = 0.5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.radius_noise = 0.2;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<double>("radius_noise", "double", 0, "standard deviation of noise to radius when generate sample map", "", &PathPublisherConfig::radius_noise)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<double>("radius_noise", "double", 0, "standard deviation of noise to radius when generate sample map", "", &PathPublisherConfig::radius_noise)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.rotation_noise = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.rotation_noise = 20.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.rotation_noise = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<double>("rotation_noise", "double", 0, "standard deviation of noise to rotation when process sample map", "", &PathPublisherConfig::rotation_noise)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<double>("rotation_noise", "double", 0, "standard deviation of noise to rotation when process sample map", "", &PathPublisherConfig::rotation_noise)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.shift_noise = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.shift_noise = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.shift_noise = 0.5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<double>("shift_noise", "double", 0, "standard deviation of noise to lateral shift base on anicar scale", "", &PathPublisherConfig::shift_noise)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<double>("shift_noise", "double", 0, "standard deviation of noise to lateral shift base on anicar scale", "", &PathPublisherConfig::shift_noise)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.local_scope = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.local_scope = 50.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.local_scope = 2.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<double>("local_scope", "double", 0, "real world width and height of local area", "", &PathPublisherConfig::local_scope)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<double>("local_scope", "double", 0, "real world width and height of local area", "", &PathPublisherConfig::local_scope)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.least_points = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.least_points = 500;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.least_points = 10;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<int>("least_points", "int", 0, "least points in image area", "", &PathPublisherConfig::least_points)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<int>("least_points", "int", 0, "least points in image area", "", &PathPublisherConfig::least_points)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.stuck_time = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.stuck_time = 20.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.stuck_time = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<double>("stuck_time", "double", 0, "max limited time the vehicle allowed to path through the path", "", &PathPublisherConfig::stuck_time)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<double>("stuck_time", "double", 0, "max limited time the vehicle allowed to path through the path", "", &PathPublisherConfig::stuck_time)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.BB_left_bottom_x = -std::numeric_limits<double>::infinity();
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.BB_left_bottom_x = std::numeric_limits<double>::infinity();
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.BB_left_bottom_x = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<double>("BB_left_bottom_x", "double", 0, "position of left bottom corner of boundary", "", &PathPublisherConfig::BB_left_bottom_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<double>("BB_left_bottom_x", "double", 0, "position of left bottom corner of boundary", "", &PathPublisherConfig::BB_left_bottom_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.BB_left_bottom_y = -std::numeric_limits<double>::infinity();
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.BB_left_bottom_y = std::numeric_limits<double>::infinity();
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.BB_left_bottom_y = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<double>("BB_left_bottom_y", "double", 0, "position of left bottom corner of boundary", "", &PathPublisherConfig::BB_left_bottom_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<double>("BB_left_bottom_y", "double", 0, "position of left bottom corner of boundary", "", &PathPublisherConfig::BB_left_bottom_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.BB_top_right_x = -std::numeric_limits<double>::infinity();
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.BB_top_right_x = std::numeric_limits<double>::infinity();
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.BB_top_right_x = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<double>("BB_top_right_x", "double", 0, "position of top right corner of boundary", "", &PathPublisherConfig::BB_top_right_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<double>("BB_top_right_x", "double", 0, "position of top right corner of boundary", "", &PathPublisherConfig::BB_top_right_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.BB_top_right_y = -std::numeric_limits<double>::infinity();
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.BB_top_right_y = std::numeric_limits<double>::infinity();
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.BB_top_right_y = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<double>("BB_top_right_y", "double", 0, "position of top right corner of boundary", "", &PathPublisherConfig::BB_top_right_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<double>("BB_top_right_y", "double", 0, "position of top right corner of boundary", "", &PathPublisherConfig::BB_top_right_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.road_length = -std::numeric_limits<double>::infinity();
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.road_length = std::numeric_limits<double>::infinity();
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.road_length = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<double>("road_length", "double", 0, "the length of sampling path in train mode when sampling path from osm file", "", &PathPublisherConfig::road_length)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<double>("road_length", "double", 0, "the length of sampling path in train mode when sampling path from osm file", "", &PathPublisherConfig::road_length)));
PathPublisherConfig::GroupDescription<PathPublisherConfig::DEFAULT::PUBLISHER_AND_SUBSCRIBER, PathPublisherConfig::DEFAULT> Publisher_and_subscriber("Publisher_and_subscriber", "", 0, 1, true, &PathPublisherConfig::DEFAULT::publisher_and_subscriber);
//#line 42 "/home/kal1-4/anicar_ws/devel/.private/path_publisher_ros_tool/share/path_publisher_ros_tool/cfg/PathPublisher.cfg"
      __min__.path_publisher_topic = "";
//#line 42 "/home/kal1-4/anicar_ws/devel/.private/path_publisher_ros_tool/share/path_publisher_ros_tool/cfg/PathPublisher.cfg"
      __max__.path_publisher_topic = "";
//#line 42 "/home/kal1-4/anicar_ws/devel/.private/path_publisher_ros_tool/share/path_publisher_ros_tool/cfg/PathPublisher.cfg"
      __default__.path_publisher_topic = "/path";
//#line 42 "/home/kal1-4/anicar_ws/devel/.private/path_publisher_ros_tool/share/path_publisher_ros_tool/cfg/PathPublisher.cfg"
      Publisher_and_subscriber.abstract_parameters.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<std::string>("path_publisher_topic", "str", 0, "Topic for path publisher", "", &PathPublisherConfig::path_publisher_topic)));
//#line 42 "/home/kal1-4/anicar_ws/devel/.private/path_publisher_ros_tool/share/path_publisher_ros_tool/cfg/PathPublisher.cfg"
      __param_descriptions__.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<std::string>("path_publisher_topic", "str", 0, "Topic for path publisher", "", &PathPublisherConfig::path_publisher_topic)));
//#line 43 "/home/kal1-4/anicar_ws/devel/.private/path_publisher_ros_tool/share/path_publisher_ros_tool/cfg/PathPublisher.cfg"
      __min__.path_publisher_queue_size = 0;
//#line 43 "/home/kal1-4/anicar_ws/devel/.private/path_publisher_ros_tool/share/path_publisher_ros_tool/cfg/PathPublisher.cfg"
      __max__.path_publisher_queue_size = 2147483647;
//#line 43 "/home/kal1-4/anicar_ws/devel/.private/path_publisher_ros_tool/share/path_publisher_ros_tool/cfg/PathPublisher.cfg"
      __default__.path_publisher_queue_size = 5;
//#line 43 "/home/kal1-4/anicar_ws/devel/.private/path_publisher_ros_tool/share/path_publisher_ros_tool/cfg/PathPublisher.cfg"
      Publisher_and_subscriber.abstract_parameters.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<int>("path_publisher_queue_size", "int", 0, "Queue size for path publisher", "", &PathPublisherConfig::path_publisher_queue_size)));
//#line 43 "/home/kal1-4/anicar_ws/devel/.private/path_publisher_ros_tool/share/path_publisher_ros_tool/cfg/PathPublisher.cfg"
      __param_descriptions__.push_back(PathPublisherConfig::AbstractParamDescriptionConstPtr(new PathPublisherConfig::ParamDescription<int>("path_publisher_queue_size", "int", 0, "Queue size for path publisher", "", &PathPublisherConfig::path_publisher_queue_size)));
//#line 124 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Publisher_and_subscriber.convertParams();
//#line 124 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(PathPublisherConfig::AbstractGroupDescriptionConstPtr(new PathPublisherConfig::GroupDescription<PathPublisherConfig::DEFAULT::PUBLISHER_AND_SUBSCRIBER, PathPublisherConfig::DEFAULT>(Publisher_and_subscriber)));
//#line 124 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(PathPublisherConfig::AbstractGroupDescriptionConstPtr(new PathPublisherConfig::GroupDescription<PathPublisherConfig::DEFAULT::PUBLISHER_AND_SUBSCRIBER, PathPublisherConfig::DEFAULT>(Publisher_and_subscriber)));
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(PathPublisherConfig::AbstractGroupDescriptionConstPtr(new PathPublisherConfig::GroupDescription<PathPublisherConfig::DEFAULT, PathPublisherConfig>(Default)));
//#line 366 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<PathPublisherConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<PathPublisherConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<PathPublisherConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    PathPublisherConfig __max__;
    PathPublisherConfig __min__;
    PathPublisherConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const PathPublisherConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static PathPublisherConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &PathPublisherConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const PathPublisherConfig &PathPublisherConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const PathPublisherConfig &PathPublisherConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const PathPublisherConfig &PathPublisherConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<PathPublisherConfig::AbstractParamDescriptionConstPtr> &PathPublisherConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<PathPublisherConfig::AbstractGroupDescriptionConstPtr> &PathPublisherConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const PathPublisherConfigStatics *PathPublisherConfig::__get_statics__()
  {
    const static PathPublisherConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = PathPublisherConfigStatics::get_instance();

    return statics;
  }

//#line 15 "/home/kal1-4/anicar_ws/devel/.private/path_publisher_ros_tool/share/path_publisher_ros_tool/cfg/PathPublisher.cfg"
      const char * const PathPublisher_debug = "debug";
//#line 16 "/home/kal1-4/anicar_ws/devel/.private/path_publisher_ros_tool/share/path_publisher_ros_tool/cfg/PathPublisher.cfg"
      const char * const PathPublisher_info = "info";
//#line 17 "/home/kal1-4/anicar_ws/devel/.private/path_publisher_ros_tool/share/path_publisher_ros_tool/cfg/PathPublisher.cfg"
      const char * const PathPublisher_warning = "warning";
//#line 18 "/home/kal1-4/anicar_ws/devel/.private/path_publisher_ros_tool/share/path_publisher_ros_tool/cfg/PathPublisher.cfg"
      const char * const PathPublisher_error = "error";
//#line 19 "/home/kal1-4/anicar_ws/devel/.private/path_publisher_ros_tool/share/path_publisher_ros_tool/cfg/PathPublisher.cfg"
      const char * const PathPublisher_fatal = "fatal";
}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __PATHPUBLISHERRECONFIGURATOR_H__
