// Generated by gencpp from file path_publisher_ros_tool/rl_control.msg
// DO NOT EDIT!


#ifndef PATH_PUBLISHER_ROS_TOOL_MESSAGE_RL_CONTROL_H
#define PATH_PUBLISHER_ROS_TOOL_MESSAGE_RL_CONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace path_publisher_ros_tool
{
template <class ContainerAllocator>
struct rl_control_
{
  typedef rl_control_<ContainerAllocator> Type;

  rl_control_()
    : done(false)
    , speed(0.0)
    , steering(0.0)  {
    }
  rl_control_(const ContainerAllocator& _alloc)
    : done(false)
    , speed(0.0)
    , steering(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _done_type;
  _done_type done;

   typedef float _speed_type;
  _speed_type speed;

   typedef float _steering_type;
  _steering_type steering;





  typedef boost::shared_ptr< ::path_publisher_ros_tool::rl_control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path_publisher_ros_tool::rl_control_<ContainerAllocator> const> ConstPtr;

}; // struct rl_control_

typedef ::path_publisher_ros_tool::rl_control_<std::allocator<void> > rl_control;

typedef boost::shared_ptr< ::path_publisher_ros_tool::rl_control > rl_controlPtr;
typedef boost::shared_ptr< ::path_publisher_ros_tool::rl_control const> rl_controlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path_publisher_ros_tool::rl_control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path_publisher_ros_tool::rl_control_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace path_publisher_ros_tool

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'path_publisher_ros_tool': ['/home/kal1-4/anicar_ws/src/path_publisher_ros_tool/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::path_publisher_ros_tool::rl_control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_publisher_ros_tool::rl_control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_publisher_ros_tool::rl_control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_publisher_ros_tool::rl_control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_publisher_ros_tool::rl_control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_publisher_ros_tool::rl_control_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path_publisher_ros_tool::rl_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7c0bd438638c70e9a1199a629bb169b5";
  }

  static const char* value(const ::path_publisher_ros_tool::rl_control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7c0bd438638c70e9ULL;
  static const uint64_t static_value2 = 0xa1199a629bb169b5ULL;
};

template<class ContainerAllocator>
struct DataType< ::path_publisher_ros_tool::rl_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_publisher_ros_tool/rl_control";
  }

  static const char* value(const ::path_publisher_ros_tool::rl_control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path_publisher_ros_tool::rl_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool done\n\
float32 speed\n\
float32 steering\n\
";
  }

  static const char* value(const ::path_publisher_ros_tool::rl_control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path_publisher_ros_tool::rl_control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.done);
      stream.next(m.speed);
      stream.next(m.steering);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rl_control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path_publisher_ros_tool::rl_control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path_publisher_ros_tool::rl_control_<ContainerAllocator>& v)
  {
    s << indent << "done: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.done);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "steering: ";
    Printer<float>::stream(s, indent + "  ", v.steering);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_PUBLISHER_ROS_TOOL_MESSAGE_RL_CONTROL_H
